hassio-addons/addon-ubuntu-base

- .gitlab-ci.yml
- base/Dockerfile
- base/build.json
Signed-off-by: Franck Nijhof <frenck@addons.community>
> ⬆️ Upgrades Ubuntu Bionic to bionic-20190424

- base/Dockerfile
Signed-off-by: Franck Nijhof <frenck@addons.community>
> ⬆️ Updates tzdata to 2019a-0ubuntu0.18.04

- base/config.json
Fixes the missing add-on slug. 😓 Happy I caught that before overwrite the actually base 😓
> Fix base image add-on slug

- base/rootfs/etc/cont-init.d/00-banner.sh
Updates the add-on start-up banner in this image to match the latest Bashio (and match the other images).
> Update add-on start-up banner

- base/Dockerfile
> :arrow_up: Upgrades tzdata to 2021a-0ubuntu0.18.04

- base/Dockerfile
Upgrades ca-certificates to 20210119~18.04.1
> :arrow_up: Upgrades ca-certificates to 20210119~18.04.1

- base/Dockerfile
- base/build.json
Upgrade base image to Ubuntu Bionic 20210118
> Upgrade base image to Ubuntu Bionic 20210118

- base/Dockerfile
Upgrades s6-overlay to v2.2.0.3
> :arrow_up: Upgrades s6-overlay to v2.2.0.3

- base/Dockerfile
- base/build.json
Upgrades Ubuntu Bionic to 202010325
> ⬆️  Upgrades Ubuntu Bionic to 202010325

- base/Dockerfile
Upgrades curl to 7.58.0-2ubuntu3.13
> ⬆️ Upgrades curl to 7.58.0-2ubuntu3.13

- base/Dockerfile
- base/build.json
Upgrades Ubuntu Bionic to 20210702
> ⬆️ Upgrades Ubuntu Bionic to 20210702

- base/Dockerfile
- base/build.json
- base/config.json
Time to upgrade to Ubuntu Focal
> :arrow_up: Upgrades base image to Ubuntu Focal

- base/Dockerfile
Upgrades tzdata to 2021e-0ubuntu0.20.04
> ⬆️ Upgrades tzdata to 2021e-0ubuntu0.20.04

- base/Dockerfile
- base/build.yaml
Upgrades Ubuntu to Focal 20211006
> :arrow_up: Upgrades Ubuntu to Focal 20211006

- base/Dockerfile
> Fix incorrect S6 Overlay root

- base/Dockerfile
- base/build.yaml
Upgrades Ubuntu to Focal 20220105
> :arrow_up: Upgrades Ubuntu to Focal 20220105

- base/Dockerfile
- base/build.yaml
Upgrades Ubuntu to Focal 20220302
> :arrow_up: Upgrades Ubuntu to Focal 20220302

- .github/workflows/deploy.yaml
- base/build.yaml
Sign this base image with Codenotary Community Attestation Service (CAS)
> :lock: Sign image with Codenotary Community Attestation Service (CAS)

- base/Dockerfile
- base/build.yaml
Upgrades Ubuntu to Focal 20220531
> :arrow_up: Upgrades Ubuntu to Focal 20220531

- base/Dockerfile
> ⬆️ Upgrades curl to 7.68.0-1ubuntu2.12

- base/Dockerfile
- base/build.yaml
Upgrades Ubuntu to Focal 20220801
> :arrow_up: Upgrades Ubuntu to Focal 20220801

- base/Dockerfile
Upgrades tzdata to 2022c-0ubuntu0.20.04.0
> ⬆️ Upgrades tzdata to 2022c-0ubuntu0.20.04.0

- base/Dockerfile
> ⬆️ Upgrades curl to 7.68.0-1ubuntu2.13

- base/Dockerfile
- base/build.yaml
> :arrow_up: Upgrades Ubuntu to Focal 20221019

- base/Dockerfile
> ⬆️ Upgrades tzdata to 2022g-0ubuntu0.20.04.1

- base/Dockerfile
- base/build.yaml
> :arrow_up: Upgrades Ubuntu to Focal 20221130

- base/Dockerfile
- base/s6-overlay/etc/s6-rc/scripts/base-addon-banner
- base/s6-overlay/etc/s6-rc/scripts/base-addon-log-level
- base/s6-overlay/etc/s6-rc/scripts/base-addon-timezone
- base/s6-overlay/etc/s6-rc/sources/base-addon-banner/type
- base/s6-overlay/etc/s6-rc/sources/base-addon-banner/up
- base/s6-overlay/etc/s6-rc/sources/base-addon-log-level/type
- base/s6-overlay/etc/s6-rc/sources/base-addon-log-level/up
- base/s6-overlay/etc/s6-rc/sources/base-addon-timezone/type
- base/s6-overlay/etc/s6-rc/sources/base-addon-timezone/up
Migrates the old style s6 init scripts in the base image to the new `s6-rc.d` style.
Existing add-ons are not affected by this change.
> :hammer: Migrate old-style base scripts s6-rc

- base/Dockerfile
> ⬆️ Upgrades curl to 7.68.0-1ubuntu2.15

- base/Dockerfile
- base/build.yaml
> ⬆️ Upgrades Ubuntu to 22.04

- .github/dependabot.yaml
- .github/renovate.json
- base/Dockerfile
> Add Renovate for dependency management

- base/Dockerfile
> Update curl to 8.5.0-2ubuntu10.6
